### ISSUE TITLE
Why did I get this result? 

### ISSUE THREAD

**Issue by functail** [KarhouTam/Federated-Averaging-PyTorch#1]
---------------------- RESULTS ----------------------
 Global FedAvg loss: 2.6197
 Global FedAvg accuracy: 0.00%
 Localized FedAvg loss: 0.4280
 Localized FedAvg accuracy: 20.00%

**Comment by KarhouTam** [comment]
Weird. I run the code again and get the results as follow:👀
(I just run `python main.py`)
---------------------- RESULTS ----------------------
 Global FedAvg loss: 2.2936
 Global FedAvg accuracy: 84.40%
 Localized FedAvg loss: 0.4877
 Localized FedAvg accuracy: 97.00%
Can you describe how you run the code and what args you had changed?

**Comment by functail** [comment]
Weird ! The same as you. `python main.py` in windows11

**Comment by KarhouTam** [comment]
Emmm... Maybe because our OS are different? I run the code in WSL2(Windows Subsystem for Linux), and that's the reason? 😂 I don't know...

**Comment by KarhouTam** [comment]
I found that your result's losses are quite similar to mine, maybe the code about displaying results have some bugs?👀 I would check that asap. Please keep tracking on this repo's updating.

**Comment by functail** [comment]
> I found that your result's losses are quite similar to mine, maybe the code about displaying results have some bugs?👀 I would check that asap. Please keep tracking on this repo's updating.

OKOK

**Comment by KarhouTam** [comment]
I run it in Win10, and get almost the same results as WSL2's. 😂 
---------------------- RESULTS ----------------------
 Global FedAvg loss: 2.2951
 Global FedAvg accuracy: 84.40%
 Localized FedAvg loss: 0.4930
 Localized FedAvg accuracy: 97.00%

So I am really confused now.😂

**Comment by functail** [comment]
Let me have an another try "from git clone ......"

**Comment by functail** [comment]
Maybe it's my gpu's fault. But when I use cpu to train the model, I meet another bug : `AttributeError: 'FedAvgTrainer' object has no attribute 'gpu'`, Luckily, I found the solution: add `self.gpu = None` to the `fedlab/core/model_maintainer.py` in line 38.

**Comment by KarhouTam** [comment]
LOL. I found that bug also, and it's okay to avoid it by defining our own device, like `self.device = next(iter(self.model.parameters())).device`. 
Change the code
`loss_g, acc_g = evaluate(model_4_eval, self.valloader, self.criterion, self.gpu)` 
to
`loss_g, acc_g = evaluate(model_4_eval, self.valloader, self.criterion, self.device)`. And it will run correctly.😄
